from __future__ import annotations

# Node labels
LABEL_SITE = 'Site'
LABEL_FACILITY = 'Facility'
LABEL_COMPONENT = 'Component'
LABEL_COMPONENT_LEGACY = 'Componenet'
LABEL_EFFORT = 'Effort'
LABEL_INFRASTRUCTURE = 'Infrastructure'
LABEL_INFRASTRUCTURE_LEGACY = 'Infrastrcture'
LABEL_REPORT = 'Report'
LABEL_MAINTENANCE = 'Maintenance'

# Relationship types
REL_DEPENDENCY = 'DEPENDENCY'
REL_INTERCHANGEABLE = 'INTERCHANGEABLE'
REL_INFLUENCE = 'INFLUENCE'
REL_CONNECTION = 'CONNECTION'
REL_CONTAINES = 'CONTAINES'
REL_HAS_REPORT = 'HAS_REPORT'
REL_HAS_MAINTENANCE = 'HAS_MAINTENANCE'

# Label groups used in Cypher filters
SITE_INFRASTRUCTURE_LABELS = (
    LABEL_SITE,
    LABEL_INFRASTRUCTURE,
    LABEL_INFRASTRUCTURE_LEGACY,
)
COMPONENT_LABELS = (
    LABEL_COMPONENT,
    LABEL_COMPONENT_LEGACY,
)
ARTIFACT_LABELS = (
    LABEL_MAINTENANCE,
    LABEL_REPORT,
)


def cypher_string_list(values: tuple[str, ...]) -> str:
    return '[' + ', '.join(f"'{value}'" for value in values) + ']'


CYPHER_SITE_INFRASTRUCTURE_LABELS = cypher_string_list(SITE_INFRASTRUCTURE_LABELS)
CYPHER_COMPONENT_LABELS = cypher_string_list(COMPONENT_LABELS)
CYPHER_ARTIFACT_LABELS = cypher_string_list(ARTIFACT_LABELS)
